name: Deploy to GitHub Pages

#------------------------------#
#--- TRIGGER ------------------#
#------------------------------#

on:
  push:
    branches: [main]
  workflow_dispatch:



#------------------------------#
#--- JOBS ---------------------#
#------------------------------#

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          
      - name: Install Dependencies
        run: npm ci
      
      # - name: Test
      #   run: npm test

      - name: Build
        run: npm run build
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
<<<<<<< HEAD
          name: pages-artifact
=======
>>>>>>> 50ead3ceeabcbfb2a68a98fc28dafd514ab6bc34
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
<<<<<<< HEAD
=======
    permissions:
      pages: write
      id-token: write
>>>>>>> 50ead3ceeabcbfb2a68a98fc28dafd514ab6bc34
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
<<<<<<< HEAD
        uses: actions/download-artifact@v4
        with:
          name: pages-artifact
=======
        uses: actions/download-pages-artifact@v3
>>>>>>> 50ead3ceeabcbfb2a68a98fc28dafd514ab6bc34

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
<<<<<<< HEAD
          token: ${{ secrets.PORTFOLIO_ACCESS_TOKEN }}
          publish_dir: ./dist
=======
          publish_dir: ./dist
>>>>>>> 50ead3ceeabcbfb2a68a98fc28dafd514ab6bc34
