name: Deploy to GitHub Pages

#------------------------------#
#--- TRIGGER ------------------#
#------------------------------#

on:
  push:
    branches: [main]
  workflow_dispatch:



#------------------------------#
#--- JOBS ---------------------#
#------------------------------#

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          
      - name: Install Dependencies
        run: npm ci
      
      # - name: Test
      #   run: npm test

      - name: Build
        run: npm run build
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: pages-artifact
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-artifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
